name = "cloudflare-search-portal"
compatibility_date = "2024-09-23"
pages_build_output_dir = "./dist"

[[d1_databases]]
binding = "DB"
database_name = "worker_1_db"
database_id = "75f396d8-bade-4393-a269-31ee32b3e072"
preview_database_id = "75f396d8-bade-4393-a269-31ee32b3e072"

[[kv_namespaces]]
binding = "KV"
id = "5ad0544c0a9148fd8697bfb20a7e0c4a"
preview_id = "5ad0544c0a9148fd8697bfb20a7e0c4a"


