name = "cloudflare-search-portal"
main = "@astrojs/cloudflare/entrypoints/server"
compatibility_date = "2026-08-15"

[[d1_databases]]
binding = "DB"
database_name = "worker_1_db"
database_id = "75f396d8-bade-4393-a269-31ee32b3e3f2"
preview_database_id = "75f396d8-bade-4393-a269-31ee32b3e3f2"

[ai]
binding = "AI"
