#!/usr/bin/env bash
set -uo pipefail

# Repository reconciliation is intentionally conservative. It reports drift by
# default and applies only hash- or structure-guarded transformations with
# `--apply`. It never commits, pushes, creates cloud resources, changes secrets,
# runs production migrations, or deploys.

CONTRACT_STARWIND_VERSION="3.1.0"
CONTRACT_STARWIND_ADAPTER_VERSION="1.1.0"
CONTRACT_CLOUDFLARE_ADAPTER_VERSION="14.2.1"
CONTRACT_VITE_VERSION="8.2.1"
CONTRACT_WORKERS_TYPES_VERSION="5.20260816.1"
MODE="audit"
FETCH=1
ROOT=""
REPORT_PATH=""

usage() {
  cat <<'EOF'
Usage:
  ./scripts/reconcile.sh                 # read-only audit
  ./scripts/reconcile.sh --apply         # apply safe deterministic changes
  ./scripts/reconcile.sh --no-fetch      # audit without fetching origin
  ./scripts/reconcile.sh --report PATH   # write machine-readable report

Exit codes:
  0  repository conforms to PROJECT_CONTRACT.md
  1  drift or an unsafe/ambiguous configuration was found
  2  usage or tooling error
EOF
}

while (($#)); do
  case "$1" in
    --apply) MODE="apply" ;;
    --audit) MODE="audit" ;;
    --no-fetch) FETCH=0 ;;
    --report)
      shift
      [[ $# -gt 0 ]] || { echo "--report requires a path" >&2; exit 2; }
      REPORT_PATH="$1"
      ;;
    --internal-apply) MODE="internal-apply" ;;
    -h|--help) usage; exit 0 ;;
    *) echo "Unknown option: $1" >&2; usage >&2; exit 2 ;;
  esac
  shift
done

command -v git >/dev/null || { echo "git is required" >&2; exit 2; }
command -v node >/dev/null || { echo "Node.js is required" >&2; exit 2; }
command -v npm >/dev/null || { echo "npm is required" >&2; exit 2; }

ROOT="$(git rev-parse --show-toplevel 2>/dev/null)" || {
  echo "Run this script from inside the repository." >&2
  exit 2
}
cd "$ROOT"

[[ -f PROJECT_CONTRACT.md ]] || { echo "PROJECT_CONTRACT.md is missing." >&2; exit 2; }
[[ -f package.json ]] || { echo "package.json is missing." >&2; exit 2; }

REPORT_PATH="${REPORT_PATH:-$ROOT/.git/production-reconcile.json}"
STATE_DIR="$(mktemp -d)"
PASS_FILE="$STATE_DIR/pass"
FAIL_FILE="$STATE_DIR/fail"
WARN_FILE="$STATE_DIR/warn"
: >"$PASS_FILE"; : >"$FAIL_FILE"; : >"$WARN_FILE"
trap 'rm -rf "$STATE_DIR"' EXIT

pass() { printf '%s\n' "$*" >>"$PASS_FILE"; printf '  ✓ %s\n' "$*"; }
fail() { printf '%s\n' "$*" >>"$FAIL_FILE"; printf '  ✗ %s\n' "$*"; }
warn() { printf '%s\n' "$*" >>"$WARN_FILE"; printf '  ! %s\n' "$*"; }

hash_file() {
  if command -v sha256sum >/dev/null; then sha256sum "$1" | awk '{print $1}';
  else shasum -a 256 "$1" | awk '{print $1}'; fi
}

pkg_value() {
  node -e '
    const p=require("./package.json");
    const path=process.argv[1].split(".");
    let value=p;
    for (const key of path) value=value?.[key];
    process.stdout.write(value == null ? "" : String(value));
  ' "$1"
}

all_package_names() {
  node -e '
    const p=require("./package.json");
    console.log(Object.keys({...p.dependencies,...p.devDependencies}).sort().join("\n"));
  '
}

major_of() {
  printf '%s' "$1" | sed -E 's/^[^0-9]*([0-9]+).*/\1/'
}

is_exact_version() {
  [[ "$1" =~ ^[0-9]+\.[0-9]+\.[0-9]+([.-][0-9A-Za-z.-]+)?$ ]]
}

node_meets_contract() {
  node -e 'const [major,minor]=process.versions.node.split(".").map(Number); process.exit(major>22 || (major===22 && minor>=12) ? 0 : 1)'
}

parse_wrangler_config() {
  local output="$1"
  node - "$output" <<'NODE'
const fs = require('fs');
const out = process.argv[2];
let path = '';
for (const candidate of ['wrangler.jsonc', 'wrangler.json', 'wrangler.toml']) {
  if (fs.existsSync(candidate)) { path = candidate; break; }
}
const result = { path, name: '', main: '', accountId: '', d1: [], kv: [], r2: [], ai: [] };
if (!path) { fs.writeFileSync(out, JSON.stringify(result)); process.exit(0); }
const text = fs.readFileSync(path, 'utf8');
if (path.endsWith('.toml')) {
  let section = null;
  let current = null;
  for (const raw of text.split(/\r?\n/)) {
    const line = raw.replace(/\s+#.*$/, '').trim();
    if (!line) continue;
    const array = line.match(/^\[\[([^\]]+)\]\]$/);
    const table = line.match(/^\[([^\]]+)\]$/);
    if (array) {
      section = array[1]; current = {};
      if (section === 'd1_databases') result.d1.push(current);
      else if (section === 'kv_namespaces') result.kv.push(current);
      else if (section === 'r2_buckets') result.r2.push(current);
      continue;
    }
    if (table) { section = table[1]; current = section === 'ai' ? {} : null; if (current) result.ai.push(current); continue; }
    const pair = line.match(/^([A-Za-z0-9_]+)\s*=\s*"([^"]*)"/);
    if (!pair) continue;
    const [, key, value] = pair;
    if (current) current[key] = value;
    else if (key === 'name') result.name = value;
    else if (key === 'main') result.main = value;
    else if (key === 'account_id') result.accountId = value;
  }
} else {
  // Wrangler JSONC generated by this project uses comments only outside strings.
  let stripped = '', inString = false, escaped = false, lineComment = false, blockComment = false;
  for (let i=0; i<text.length; i++) {
    const c=text[i], n=text[i+1];
    if (lineComment) { if (c==='\n') { lineComment=false; stripped+=c; } continue; }
    if (blockComment) { if (c==='*' && n==='/') { blockComment=false; i++; } continue; }
    if (!inString && c==='/' && n==='/') { lineComment=true; i++; continue; }
    if (!inString && c==='/' && n==='*') { blockComment=true; i++; continue; }
    stripped += c;
    if (inString) { if (escaped) escaped=false; else if (c==='\\') escaped=true; else if (c==='"') inString=false; }
    else if (c==='"') inString=true;
  }
  const cfg=JSON.parse(stripped);
  result.name=cfg.name || ''; result.main=cfg.main || ''; result.accountId=cfg.account_id || '';
  result.d1=cfg.d1_databases || []; result.kv=cfg.kv_namespaces || [];
  result.r2=cfg.r2_buckets || []; result.ai=cfg.ai ? [cfg.ai] : [];
}
fs.writeFileSync(out, JSON.stringify(result, null, 2));
NODE
}

json_get() {
  node -e '
    const fs=require("fs"), data=JSON.parse(fs.readFileSync(process.argv[1],"utf8"));
    let value=data;
    for (const part of process.argv[2].split(".")) value=value?.[part];
    if (Array.isArray(value)) process.stdout.write(String(value.length));
    else process.stdout.write(value == null ? "" : String(value));
  ' "$1" "$2"
}

emit_report() {
  mkdir -p "$(dirname "$REPORT_PATH")"
  node - "$PASS_FILE" "$FAIL_FILE" "$WARN_FILE" "$REPORT_PATH" "$MODE" <<'NODE'
const fs=require('fs');
const lines=(p)=>fs.readFileSync(p,'utf8').split(/\r?\n/).filter(Boolean);
const [passFile,failFile,warnFile,out,mode]=process.argv.slice(2);
const report={
  schemaVersion: 1,
  generatedAt: new Date().toISOString(),
  mode,
  repository: {
    branch: process.env.RECONCILE_BRANCH || '',
    head: process.env.RECONCILE_HEAD || '',
    originMain: process.env.RECONCILE_ORIGIN_MAIN || '',
    clean: process.env.RECONCILE_CLEAN === 'true'
  },
  stack: {
    astro: process.env.RECONCILE_ASTRO || '',
    tailwind: process.env.RECONCILE_TAILWIND || '',
    adapter: process.env.RECONCILE_ADAPTER || '',
    ui: 'starwind',
    uiVersion: '3.1.0'
  },
  configuration: {
    wrangler: process.env.RECONCILE_WRANGLER || '',
    productionD1Id: process.env.RECONCILE_D1_PROD || '',
    previewD1Id: process.env.RECONCILE_D1_PREVIEW || '',
    rateLimitKvId: process.env.RECONCILE_RATE_KV || ''
  },
  pass: lines(passFile),
  failures: lines(failFile),
  warnings: lines(warnFile),
  conformant: lines(failFile).length === 0
};
fs.writeFileSync(out, JSON.stringify(report,null,2)+'\n');
NODE
  printf '\nMachine-readable report: %s\n' "$REPORT_PATH"
}

apply_known_changes() {
  echo "Applying deterministic transformations in temporary worktree..."

  node_meets_contract || { echo "Conflict: Node.js 22.12 or newer is required." >&2; return 1; }

  # Preconditions: do not reinterpret a different stack as this contract.
  local astro tailwind adapter
  astro="$(pkg_value dependencies.astro)"
  tailwind="$(pkg_value devDependencies.tailwindcss)"
  adapter="$(pkg_value dependencies.@astrojs/cloudflare)"
  [[ "$(major_of "$astro")" == "7" ]] || { echo "Conflict: Astro is not 7.x" >&2; return 1; }
  [[ "$(major_of "$tailwind")" == "4" ]] || { echo "Conflict: Tailwind is not 4.x" >&2; return 1; }
  [[ -n "$adapter" ]] || { echo "Conflict: Cloudflare adapter is absent" >&2; return 1; }
  grep -q "@tailwindcss/vite" astro.config.mjs || { echo "Conflict: Tailwind Vite integration is absent" >&2; return 1; }
  grep -q "cloudflare" astro.config.mjs || { echo "Conflict: Workers adapter integration is absent" >&2; return 1; }

  local competing
  competing="$(all_package_names | grep -E '^(daisyui|bootstrap|flowbite|@mui/|@chakra-ui/|@skeletonlabs/|shadcn)' || true)"
  [[ -z "$competing" ]] || { echo "Conflict: competing UI packages detected: $competing" >&2; return 1; }

  # Structural JSON update: exact pins and contract entry points only.
  node - <<NODE
const fs=require('fs');
const p=JSON.parse(fs.readFileSync('package.json','utf8'));
p.scripts={...p.scripts,
  'contract:audit':'./scripts/reconcile.sh --no-fetch',
  'verify:production':'./scripts/verify-production.sh'
};
p.dependencies={...p.dependencies,
  '@astrojs/cloudflare':'${CONTRACT_CLOUDFLARE_ADAPTER_VERSION}',
  '@starwind-ui/astro':'${CONTRACT_STARWIND_ADAPTER_VERSION}',
  'vite':'${CONTRACT_VITE_VERSION}'
};
p.devDependencies={...p.devDependencies,
  'starwind':'${CONTRACT_STARWIND_VERSION}',
  '@cloudflare/workers-types':'${CONTRACT_WORKERS_TYPES_VERSION}'
};
// pdf-parse was used only by the hash-allowlisted one-off extraction artifacts.
delete p.dependencies?.['pdf-parse'];
fs.writeFileSync('package.json', JSON.stringify(p,null,2)+'\n');
NODE

  # Replace only the known legacy CI file, or leave an already reconciled file
  # alone. Any independently edited workflow is a conflict for human review.
  local legacy_ci_hash="7a498fcf616f4c5fca3c93dfaa68dea93a3096b6c192604c8ed42a029c6504e3"
  if grep -q 'verify-production.sh --production' .github/workflows/ci.yml 2>/dev/null; then
    echo "  CI workflow already invokes the production contract gate."
  elif [[ -f .github/workflows/ci.yml && "$(hash_file .github/workflows/ci.yml)" == "$legacy_ci_hash" ]]; then
    cat >.github/workflows/ci.yml <<'YAML'
name: CI

on:
  pull_request:
  push:
    branches: [main]

permissions:
  contents: read

concurrency:
  group: cloudflare-search-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  EXPECTED_CF_ACCOUNT_ID: ${{ vars.CLOUDFLARE_ACCOUNT_ID }}
  EXPECTED_PRODUCTION_D1_ID: ${{ vars.PRODUCTION_D1_ID }}
  EXPECTED_PREVIEW_D1_ID: ${{ vars.PREVIEW_D1_ID }}
  EXPECTED_RATE_LIMIT_KV_ID: ${{ vars.RATE_LIMIT_KV_ID }}
  INGEST_ALLOWED_HOSTS: ${{ vars.INGEST_ALLOWED_HOSTS }}

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 22.19.0
          cache: npm
      - run: npm ci --ignore-scripts --no-audit --no-fund
      - name: Generate config from confirmed IDs
        run: node scripts/configure-cloudflare.mjs --write
      - run: ./scripts/verify-production.sh --skip-install

  deploy:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    needs: verify
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 22.19.0
          cache: npm
      - run: npm ci --ignore-scripts --no-audit --no-fund
      - name: Generate config from confirmed IDs
        run: node scripts/configure-cloudflare.mjs --write
      - name: Re-verify pushed production state
        run: ./scripts/verify-production.sh --production --skip-install
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ vars.CLOUDFLARE_ACCOUNT_ID }}
      - name: Deploy Worker
        run: ./node_modules/.bin/wrangler deploy
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ vars.CLOUDFLARE_ACCOUNT_ID }}
YAML
    echo "  replaced hash-verified legacy CI workflow."
  else
    echo "Conflict: CI workflow differs from the allowlisted legacy file; left untouched." >&2
  fi

  # Delete only artifacts whose exact current content is allowlisted below.
  local entries=(
    "8c7c9cafbe5313eb5e2d5579b290f8388743226ce5efab52706ca53f7b590f53|Untitled Project - Track 1 - Treblo-2.mp3"
    "a6aa53082b3245a701fcebc9be674733a142389714cb6e810bc0da533ffd260d|extract_pdf.js"
    "d45d2739e116830018b9b0a3462fce376e6b2e73281c6badb1d55cd3922bc1df|extract_pdf.cjs"
    "b2c2224dce22ce066b8be9d1aab27d69df83fd53b16da8d287aaad691f45f52a|extracted.txt"
    "44077109ea00c79917da4917e0d21dcc5e47c69cfb8fb6c90ab492b791da5210|generate_payloads.js"
    "0f22c6f66066d2992db1e43c8520908f184e35f17148b4139e97159652238f46|insert.sql"
    "610003bc516a251bc206fe237b20773ff7d8bb8d4aa126e8665fbe26268c1928|kv.json"
    "adba7659eec9e66d8219e79f149eb4983ccee0deaf456f82998571ba83d3c909|autoloop.sh"
    "448818547d352b122b638bbe12b5cef0200473c76a7ed6e5024b676c459e071d|self-heal.sh"
    "005a0ac424ee0b7c20ef3339f6baa119126215280ceb1a2b90ca4c709677c9cc|verify.sh"
    "2468ff2b47ee823b06aceb17339f691cccb3ce9ed1ddce1618e4841de14f4ad2|tailwind.config.js"
  )
  local entry expected path actual
  for entry in "${entries[@]}"; do
    expected="${entry%%|*}"; path="${entry#*|}"
    [[ -e "$path" ]] || continue
    actual="$(hash_file "$path")"
    if [[ "$actual" == "$expected" ]]; then
      rm -- "$path"
      echo "  removed allowlisted artifact: $path"
    else
      echo "Conflict: $path is a known artifact path but its content changed; left untouched." >&2
    fi
  done

  # Resolve exactly what package.json declares and produce the lockfile. The
  # verification script performs the clean npm ci installation afterward.
  npm install --package-lock-only --ignore-scripts --no-audit --no-fund
}

if [[ "$MODE" == "internal-apply" ]]; then
  apply_known_changes
  exit $?
fi

printf 'Project contract reconciliation (%s)\n' "$MODE"
printf 'Repository: %s\n\n' "$ROOT"

BRANCH="$(git branch --show-current 2>/dev/null || true)"
HEAD_COMMIT="$(git rev-parse HEAD)"
ORIGIN_MAIN=""
CLEAN=true
[[ -z "$(git status --porcelain --untracked-files=normal)" ]] || CLEAN=false
# Bootstrap exception: the first invocation may run before the three governance
# files themselves are committed. No application/config change gets this waiver.
NON_BOOTSTRAP_DIRTY="$(git status --porcelain --untracked-files=all | grep -Ev '^\?\? (PROJECT_CONTRACT\.md|scripts/reconcile\.sh|scripts/verify-production\.sh)$' || true)"
APPLY_TREE_SAFE=false
[[ "$CLEAN" == true || -z "$NON_BOOTSTRAP_DIRTY" ]] && APPLY_TREE_SAFE=true
export RECONCILE_BRANCH="$BRANCH" RECONCILE_HEAD="$HEAD_COMMIT" RECONCILE_CLEAN="$CLEAN"

if ((FETCH)); then
  echo "[git]"
  if git remote get-url origin >/dev/null 2>&1 && git fetch origin --prune; then
    pass "Fetched origin."
  else
    fail "Could not fetch origin; repository ancestry is unverified."
  fi
fi
if git show-ref --verify --quiet refs/remotes/origin/main; then
  ORIGIN_MAIN="$(git rev-parse origin/main)"
  export RECONCILE_ORIGIN_MAIN="$ORIGIN_MAIN"
  if [[ "$HEAD_COMMIT" == "$ORIGIN_MAIN" ]]; then pass "HEAD matches origin/main."
  elif git merge-base --is-ancestor origin/main HEAD; then warn "Local main is ahead of origin/main."
  elif git merge-base --is-ancestor HEAD origin/main; then fail "Local checkout is behind origin/main."
  else fail "Local checkout has diverged from origin/main."; fi
else
  fail "origin/main does not exist locally."
fi
if [[ "$BRANCH" == "main" ]]; then
  pass "Checked-out branch is main."
elif [[ "${GITHUB_ACTIONS:-}" == "true" && "${GITHUB_EVENT_NAME:-}" == "pull_request" ]]; then
  pass "Detached GitHub pull-request checkout is permitted for read-only audit."
else
  fail "Checked-out branch is '${BRANCH:-detached}', not main."
fi

if [[ "$MODE" == "apply" ]]; then
  if [[ "$BRANCH" != "main" || "$APPLY_TREE_SAFE" != true || -z "$ORIGIN_MAIN" || "$HEAD_COMMIT" != "$ORIGIN_MAIN" ]]; then
    fail "--apply requires main at origin/main with no changes except an initial uncommitted copy of the three governance files."
    emit_report
    exit 1
  fi

  WORK_ROOT="$(mktemp -d)"
  WORKTREE="$WORK_ROOT/worktree"
  PATCH="$WORK_ROOT/reconcile.patch"
  echo
  echo "[apply] Creating detached temporary worktree snapshot..."
  if ! git worktree add --quiet --detach "$WORKTREE" "$HEAD_COMMIT"; then
    fail "Unable to create temporary worktree."
    emit_report
    rm -rf "$WORK_ROOT"
    exit 1
  fi
  if [[ ! -x "$WORKTREE/scripts/reconcile.sh" ]]; then
    # One-time bootstrap: copy only the governance implementation. These paths
    # are excluded from the generated application patch and remain for review.
    mkdir -p "$WORKTREE/scripts"
    cp "$ROOT/PROJECT_CONTRACT.md" "$WORKTREE/PROJECT_CONTRACT.md"
    cp "$ROOT/scripts/reconcile.sh" "$WORKTREE/scripts/reconcile.sh"
    cp "$ROOT/scripts/verify-production.sh" "$WORKTREE/scripts/verify-production.sh"
    chmod +x "$WORKTREE/scripts/reconcile.sh" "$WORKTREE/scripts/verify-production.sh"
  fi
  if (cd "$WORKTREE" && ./scripts/reconcile.sh --internal-apply); then
    git -C "$WORKTREE" add -A
    git -C "$WORKTREE" diff --cached --binary -- . \
      ':(exclude)PROJECT_CONTRACT.md' \
      ':(exclude)scripts/reconcile.sh' \
      ':(exclude)scripts/verify-production.sh' >"$PATCH"
    git worktree remove --force "$WORKTREE"
    if [[ -s "$PATCH" ]] && git apply --check "$PATCH" && git apply "$PATCH"; then
      pass "Applied the verified temporary-worktree patch to main."
    elif [[ ! -s "$PATCH" ]]; then
      pass "No deterministic changes were needed."
    else
      fail "Generated patch did not apply cleanly; main was left unchanged."
    fi
  else
    git worktree remove --force "$WORKTREE" >/dev/null 2>&1 || true
    fail "Deterministic reconciliation failed in the temporary worktree; main was left unchanged."
  fi
  rm -rf "$WORK_ROOT"
  echo
  echo "Auditing the reconciled working tree; unresolved conflicts remain read-only."
  exec "$ROOT/scripts/reconcile.sh" --no-fetch --report "$REPORT_PATH"
fi

echo
echo "[stack]"
NODE_VERSION="$(node --version | sed 's/^v//')"
node_meets_contract && pass "Node.js meets the >=22.12 contract ($NODE_VERSION)." || fail "Node.js 22.12 or newer is required; found $NODE_VERSION."
ASTRO_VERSION="$(pkg_value dependencies.astro)"
TAILWIND_VERSION="$(pkg_value devDependencies.tailwindcss)"
ADAPTER_VERSION="$(pkg_value dependencies.@astrojs/cloudflare)"
VITE_VERSION="$(pkg_value dependencies.vite)"
export RECONCILE_ASTRO="$ASTRO_VERSION" RECONCILE_TAILWIND="$TAILWIND_VERSION" RECONCILE_ADAPTER="$ADAPTER_VERSION"
[[ "$(major_of "$ASTRO_VERSION")" == "7" ]] && pass "Astro is 7.x ($ASTRO_VERSION)." || fail "Astro must be 7.x; found '${ASTRO_VERSION:-missing}'."
[[ "$VITE_VERSION" == "$CONTRACT_VITE_VERSION" ]] && pass "Vite matches Astro 7 ($VITE_VERSION)." || fail "Vite must be $CONTRACT_VITE_VERSION; found '${VITE_VERSION:-missing}'."
[[ "$(major_of "$TAILWIND_VERSION")" == "4" ]] && pass "Tailwind is 4.x ($TAILWIND_VERSION)." || fail "Tailwind must be 4.x; found '${TAILWIND_VERSION:-missing}'."
[[ "$ADAPTER_VERSION" == "$CONTRACT_CLOUDFLARE_ADAPTER_VERSION" ]] && grep -q "cloudflare" astro.config.mjs && pass "Current Cloudflare adapter is configured ($ADAPTER_VERSION)." || fail "Cloudflare adapter must be $CONTRACT_CLOUDFLARE_ADAPTER_VERSION for Astro 7; found '${ADAPTER_VERSION:-missing}'."
grep -q "output:[[:space:]]*['\"]server['\"]" astro.config.mjs && pass "Astro SSR output is enabled." || fail "Astro output must be server/SSR."
grep -q "@tailwindcss/vite" astro.config.mjs && grep -q '@import "tailwindcss"' src/styles/starwind.css && pass "Tailwind 4 Vite/CSS integration is present." || fail "Tailwind 4 integration is incomplete."

if [[ -f package-lock.json ]]; then pass "npm lockfile exists."; else fail "package-lock.json is missing."; fi
while IFS=$'\t' read -r name version; do
  [[ -z "$name" ]] && continue
  if is_exact_version "$version"; then :; else fail "Dependency $name is not exactly pinned ($version)."; fi
done < <(node -e 'const p=require("./package.json"); for (const [n,v] of Object.entries({...p.dependencies,...p.devDependencies})) console.log(`${n}\t${v}`)')

echo
echo "[ui]"
STARWIND_VERSION="$(pkg_value devDependencies.starwind)"
STARWIND_ADAPTER_VERSION="$(pkg_value dependencies.@starwind-ui/astro)"
[[ "$STARWIND_VERSION" == "$CONTRACT_STARWIND_VERSION" ]] && pass "Starwind CLI is pinned to $CONTRACT_STARWIND_VERSION." || fail "Starwind must be pinned to $CONTRACT_STARWIND_VERSION; found '${STARWIND_VERSION:-missing}'."
[[ "$STARWIND_ADAPTER_VERSION" == "$CONTRACT_STARWIND_ADAPTER_VERSION" ]] && pass "Starwind Astro adapter is pinned to $CONTRACT_STARWIND_ADAPTER_VERSION." || fail "@starwind-ui/astro must be $CONTRACT_STARWIND_ADAPTER_VERSION; found '${STARWIND_ADAPTER_VERSION:-missing}'."
if [[ -f starwind.config.json ]] && node -e 'const c=require("./starwind.config.json"); process.exit(c.tailwind?.css==="src/styles/starwind.css" && c.componentDir==="src/components/starwind" ? 0 : 1)'; then
  pass "Starwind configuration points to canonical paths."
else
  fail "Starwind configuration does not point to canonical CSS/component paths."
fi
STARWIND_COMPONENTS="$(find src/components/starwind -type f -name '*.astro' -size +100c 2>/dev/null | wc -l | tr -d ' ')"
[[ "$STARWIND_COMPONENTS" -gt 0 ]] && pass "Substantive Starwind Astro components exist ($STARWIND_COMPONENTS)." || fail "No substantive Starwind Astro component is installed."
if grep -R -E "from ['\"](@/|\.\.?/).*components/starwind|from ['\"]@/components/starwind" src --include='*.astro' --exclude-dir=starwind >/dev/null 2>&1; then
  pass "Application code imports Starwind components."
else
  fail "Starwind component files exist but are not used by the application."
fi
if grep -q '@theme[[:space:]]\+inline' src/styles/starwind.css && grep -q -- '--color-primary:' src/styles/starwind.css; then
  pass "Starwind/Tailwind theme mappings are present."
else
  fail "Shared CSS lacks Starwind Tailwind-4 theme mappings."
fi
COMPETING="$(all_package_names | grep -E '^(daisyui|bootstrap|flowbite|@mui/|@chakra-ui/|@skeletonlabs/|shadcn)' || true)"
[[ -z "$COMPETING" ]] && pass "No competing UI package is installed." || fail "Competing UI packages are installed: $COMPETING"
if [[ -f tailwind.config.js ]] && grep -Eq 'daisyui|typography' tailwind.config.js; then fail "Stale Tailwind/DaisyUI configuration remains."; fi

CONFIG_JSON="$STATE_DIR/wrangler.json"
parse_wrangler_config "$CONFIG_JSON"
WRANGLER_PATH="$(json_get "$CONFIG_JSON" path)"
export RECONCILE_WRANGLER="$WRANGLER_PATH"
echo
echo "[cloudflare configuration]"
[[ -n "$WRANGLER_PATH" ]] && pass "Wrangler config detected: $WRANGLER_PATH." || fail "Wrangler configuration is missing."
WRANGLER_MAIN="$(json_get "$CONFIG_JSON" main)"
[[ "$WRANGLER_MAIN" == *"@astrojs/cloudflare/entrypoints/server"* ]] && pass "Wrangler targets the Astro Worker entrypoint." || fail "Wrangler is not configured for the Astro Worker entrypoint."
D1_COUNT="$(json_get "$CONFIG_JSON" d1)"
DB_INDEX="$(node -e 'const c=require(process.argv[1]); console.log(c.d1.findIndex(x=>x.binding==="DB"))' "$CONFIG_JSON")"
if [[ "$DB_INDEX" -ge 0 ]]; then
  D1_PROD="$(json_get "$CONFIG_JSON" "d1.$DB_INDEX.database_id")"
  D1_PREVIEW="$(json_get "$CONFIG_JSON" "d1.$DB_INDEX.preview_database_id")"
  export RECONCILE_D1_PROD="$D1_PROD" RECONCILE_D1_PREVIEW="$D1_PREVIEW"
  [[ -n "$D1_PROD" ]] && pass "DB production database ID is declared." || fail "DB database_id is missing."
  [[ -n "$D1_PREVIEW" ]] && pass "DB preview database ID is declared." || fail "DB preview_database_id is missing."
  [[ -n "$D1_PROD" && -n "$D1_PREVIEW" && "$D1_PROD" != "$D1_PREVIEW" ]] && pass "Production and preview D1 IDs are distinct." || fail "preview_database_id equals database_id (or is missing); deployment is blocked."
else
  D1_PROD=""; D1_PREVIEW=""; fail "Exactly one D1 binding named DB is required."
fi
RATE_INDEX="$(node -e 'const c=require(process.argv[1]); console.log(c.kv.findIndex(x=>x.binding==="RATE_LIMIT"))' "$CONFIG_JSON")"
if [[ "$RATE_INDEX" -ge 0 ]]; then
  RATE_KV="$(json_get "$CONFIG_JSON" "kv.$RATE_INDEX.id")"
  export RECONCILE_RATE_KV="$RATE_KV"
  [[ -n "$RATE_KV" ]] && pass "Dedicated RATE_LIMIT KV binding is declared." || fail "RATE_LIMIT KV namespace ID is missing."
else
  RATE_KV=""; fail "Dedicated KV binding RATE_LIMIT is missing."
fi
DUPLICATE_KV="$(node -e 'const c=require(process.argv[1]); const ids=c.kv.map(x=>x.id).filter(Boolean); console.log(ids.length-new Set(ids).size)' "$CONFIG_JSON")"
[[ "$DUPLICATE_KV" == "0" ]] && pass "KV namespace IDs are unique." || fail "Two or more KV bindings share a namespace ID."
R2_COUNT="$(json_get "$CONFIG_JSON" r2)"
[[ "$R2_COUNT" == "0" ]] && pass "No uncontracted R2 binding is declared." || fail "R2 bindings require a contract revision."

if [[ -n "${EXPECTED_PRODUCTION_D1_ID:-}" ]]; then
  [[ "$D1_PROD" == "$EXPECTED_PRODUCTION_D1_ID" ]] && pass "D1 production ID matches operator confirmation." || fail "D1 production ID disagrees with EXPECTED_PRODUCTION_D1_ID."
else warn "EXPECTED_PRODUCTION_D1_ID is unset; production identity is not operator-confirmed."; fi
if [[ -n "${EXPECTED_PREVIEW_D1_ID:-}" ]]; then
  [[ "$D1_PREVIEW" == "$EXPECTED_PREVIEW_D1_ID" ]] && pass "D1 preview ID matches operator confirmation." || fail "D1 preview ID disagrees with EXPECTED_PREVIEW_D1_ID."
else warn "EXPECTED_PREVIEW_D1_ID is unset; preview identity is not operator-confirmed."; fi
if [[ -n "${EXPECTED_RATE_LIMIT_KV_ID:-}" ]]; then
  [[ "$RATE_KV" == "$EXPECTED_RATE_LIMIT_KV_ID" ]] && pass "RATE_LIMIT ID matches operator confirmation." || fail "RATE_LIMIT ID disagrees with EXPECTED_RATE_LIMIT_KV_ID."
else warn "EXPECTED_RATE_LIMIT_KV_ID is unset; KV identity is not operator-confirmed."; fi


echo
echo "[security and retrieval]"
for route in upload crawl; do
  file="src/pages/api/$route.ts"
  if [[ -f "$file" ]] && grep -Eq 'require(Ingest|Api)Auth' "$file" && \
     grep -q 'INGEST_TOKEN' "$file" && grep -R -q 'INGEST_TOKEN' src/lib --include='*.ts'; then
    pass "/api/$route requires INGEST_TOKEN authentication."
  else
    fail "/api/$route does not visibly enforce fail-closed INGEST_TOKEN authentication."
  fi
done
if [[ -f src/pages/api/chat.ts ]] && grep -Eq 'require(Chat|Api|Bearer)?Auth|requireAuth' src/pages/api/chat.ts && \
   grep -R -q 'CHAT_TOKEN' src/lib --include='*.ts'; then
  pass "/api/chat requires CHAT_TOKEN authentication."
else
  fail "/api/chat does not visibly enforce fail-closed CHAT_TOKEN authentication."
fi
if [[ -f src/lib/security.ts ]] && grep -q "redirect: 'manual'\|redirect: \"manual\"" src/lib/security.ts && grep -Eq 'INGEST_ALLOWED_HOSTS|allowedHosts' src/lib/security.ts && grep -Eq 'private|PublicIp|public address' src/lib/security.ts; then
  pass "Shared crawler security includes allowlisting, address checks, and manual redirects."
else
  fail "Shared SSRF-safe fetch boundary is missing or incomplete."
fi
if grep -R -q 'RATE_LIMIT' src/pages/api/{upload,crawl,chat}.ts 2>/dev/null && grep -R -Eq 'rateLimit|RateLimit|enforceRate' src/lib src/pages/api 2>/dev/null; then
  pass "Protected APIs use the dedicated rate-limit binding."
else
  fail "Protected APIs do not visibly enforce dedicated KV rate limits."
fi
if [[ -f src/lib/retrieval.ts ]] && grep -q 'retrieval' src/pages/api/search.ts && grep -q 'retrieval' src/pages/api/chat.ts; then
  pass "Search and chat share one retrieval module."
else
  fail "Search and chat do not share one retrieval module."
fi
if grep -Eq 'AND' src/lib/fts.ts && grep -Eq 'OR' src/lib/fts.ts; then pass "FTS helper exposes AND-first/OR-fallback construction."; else fail "FTS query ladder is missing."; fi
if grep -q '503' src/pages/api/health.ts && ! grep -A8 -E 'catch' src/pages/api/health.ts | grep -q 'ok: true'; then pass "Health failures return an unhealthy status."; else fail "Health endpoint can report a false healthy response."; fi


echo
echo "[migrations, tests, and CI]"
mapfile -t MIGRATIONS < <(find migrations -maxdepth 1 -type f -name '[0-9][0-9][0-9][0-9]_*.sql' -printf '%f\n' 2>/dev/null | sort)
MIGRATION_OK=true
EXPECTED=0
for migration in "${MIGRATIONS[@]}"; do
  number="${migration%%_*}"
  if ((10#$number != EXPECTED)); then MIGRATION_OK=false; break; fi
  EXPECTED=$((EXPECTED+1))
done
[[ ${#MIGRATIONS[@]} -gt 0 && "$MIGRATION_OK" == true ]] && pass "Migration numbering is deterministic and contiguous (${#MIGRATIONS[@]} files)." || fail "Migration numbering is missing, duplicated, or non-contiguous."
[[ -f migrations/0003_fix_documents_fts_update.sql ]] && grep -q "old.title" migrations/0003_fix_documents_fts_update.sql && pass "FTS update-trigger repair migration exists." || fail "FTS update-trigger repair migration is missing."
TEST_SCRIPT="$(pkg_value scripts.test)"; SECURITY_SCRIPT="$(pkg_value scripts.test:security)"; MIGRATION_SCRIPT="$(pkg_value scripts.test:migrations)"
[[ -n "$TEST_SCRIPT" ]] && pass "Unit test script is declared." || fail "package.json has no unit test script."
[[ -n "$SECURITY_SCRIPT" ]] && pass "Security test script is declared." || fail "package.json has no security test script."
[[ -n "$MIGRATION_SCRIPT" ]] && pass "Migration test script is declared." || fail "package.json has no migration test script."
if [[ -f .github/workflows/ci.yml ]] && grep -q 'npm ci' .github/workflows/ci.yml && {
  grep -q 'verify-production.sh' .github/workflows/ci.yml || {
    grep -q 'test:security' .github/workflows/ci.yml &&
    grep -q 'test:migrations' .github/workflows/ci.yml &&
    grep -q 'npm run build' .github/workflows/ci.yml
  }
}; then
  pass "CI contains the contract verification gate."
else
  fail "CI does not implement the contract verification pipeline."
fi


echo
echo "[repository hygiene]"
JUNK=("Untitled Project - Track 1 - Treblo-2.mp3" extract_pdf.js extract_pdf.cjs extracted.txt generate_payloads.js insert.sql kv.json autoloop.sh self-heal.sh verify.sh)
JUNK_FOUND=()
for path in "${JUNK[@]}"; do [[ -e "$path" ]] && JUNK_FOUND+=("$path"); done
[[ ${#JUNK_FOUND[@]} -eq 0 ]] && pass "Known root artifacts are absent." || fail "Known root artifacts remain: ${JUNK_FOUND[*]}"
if git diff --check >/dev/null; then pass "Git diff has no whitespace errors."; else fail "Git diff contains whitespace errors."; fi

emit_report
FAIL_COUNT="$(wc -l <"$FAIL_FILE" | tr -d ' ')"
WARN_COUNT="$(wc -l <"$WARN_FILE" | tr -d ' ')"
printf '\nResult: %s failure(s), %s warning(s).\n' "$FAIL_COUNT" "$WARN_COUNT"
if [[ "$FAIL_COUNT" == "0" ]]; then
  echo "Repository conforms to PROJECT_CONTRACT.md."
  exit 0
fi
echo "Repository does not conform. No files were changed."
echo "Run with --apply for safe deterministic changes; remaining conflicts require review."
exit 1
